### ISSUE TITLE
Blog Project Plan

### ISSUE THREAD

**Issue by thuang2023** [stat231-f21/blog_THeHe#1]
### **Blog Project Plan**
Yes, our blog project will be an extension of our mid-semester project. 

We are firstly interested in using the five COVID state restrictions datasets from the mid-semester project to create a network between states, showing how related they were in terms of sharing different COVID restrictions (mask mandates, bar restrictions, restaurant restrictions, gathering bans, and stay-at-home orders) during the year of 2020. This will be defined as the number of days within 2020 where states shared the same restrictions. This will most likely be a Shiny app component so users can firstly decide whether they want to look at the United States as a whole or different states. The network will be interactive, where users can control the restrictions they are looking at. There will also be a feature where users can add or remove nodes on the network to explore only the states they want to look at, and a feature where users can drag the network around to explore it at different vantage points.

We are additionally interested in seeing how unsupervised methods would cluster individuals based on their responses to anxiety, depression, and mental health resource questions (5 variables total). For example, we expected to see differences between racial/ethnic groups - would clustering reflect this? Would it reflect geographical regions? Or something entirely different or nothing at all? For this, we will consider returning to using the ranking choices for these variables (1-4) rather than the “yes” (2-4) or “no” (1) distinction. If we use only three response questions at a time for clustering, it would be possible to visualize clusters through a “3D” plot. This would also provide the chance for an interactive Shiny app where the user changes the three response variables (out of 5) to cluster on. Along the same vein, we could utilize dimensionality reduction to identify the most pertinent information and drop other information. Otherwise, clusters could be visualized in a bulleted list or accompanied by summary statistics (i.e. percent of clustered group experiencing anxiety/depression or having mental health care access). 

If there are meaningful clusters, this could be further accompanied by a network between the identified clusters where edges would be weighted by variables used to identify clusters. The initial connection between nodes would be determined by whether or not at least one individual in either cluster experienced the same symptoms (i.e., if we use the “yes/no” distinction for the 5 response variables, all nodes would be connected unless there were only two clusters, where, in the first, all individuals said “no” to all 5 response questions, and in the second, all individuals said “yes” to all 5 response questions). The weighting of connections (represented through width or more likely a continuous color palette) would be determined by how similar the proportions of individuals experiencing depression/anxiety or receiving mental health care are between two groups. One option for this would be to calculate the difference between proportions between clusters - the smaller the difference, the more connected. Interactively, one may choose whether to weight on all response variables or only some, to see how the relationship may change. 

Lastly, we aim to explore questions regarding the way that Americans thought about the pandemic itself through text analysis. While the Pulse data provides us with a lot of qualitative information, it struggles to display how the United States was thinking about COVID-19 as the pandemic raged. The dataset is able to quantify certain measures of the effect of the pandemic, such as unemployment, physical health, mental health, and income. But often, these measurements are not reliable indicators of how the pandemic was affecting Americans. More pertinently, not all Americans were thinking about the pandemic in the same way. It seems obvious that different parts of the country had different responses to the pandemic, but what were they exactly? Who was positive about certain developments, like masking, or vaccines, and who opposed these measures? Do specific phrases appear again and again in certain news media? This is something that we can explore qualitatively in a display such as word clouds for different states at various points in time, or qualitatively using summary statistics to give an overview of common trends. We can also combine text analysis with maps to map different sentiment analyses from different news sources across the country. Data sources would be local newspapers and maybe social media data from different states. 				
					 
We hope that our final product will include a published Shiny application with interactive components from clustering, networks, and maps with text analysis, and the common theme around our Shiny app will be taking a deeper dive into exploring different COVID-related relationships. 	
	
### **Schedule**
 Our first checkpoint will be on Tuesday November 9th, and will be a check in on whether we have wrangled the datasets necessary to create the individual components of the project and started working on creating the individual components. Our second checkpoint will be on Thursday November 11th as a second check in on whether we have completed the necessary wrangling and started working on the individual components. Our third checkpoint will be on Tuesday November 16th, and will be a check in to see whether we have completed or are close to completing our individual components. Our fourth checkpoint will be on Thursday November 18th to check in on whether we have completed our individual components and started on writing our blog content. Over Thanksgiving break, we will finalize the aesthetics and writing of our blog, and start on practicing our presentation, which is on the 30th. 

- Specifically for November 9th, Tracy will wrangle all five of the restrictions datasets so they can be transformed into an igraph that can then be used to create networks. This means that the datasets should all have three columns, where the first two columns are the states, and the third column is the number of days within 2020 where the states shared the same type of restrictions amongst mask mandates, gathering bans, etc. She will also start on creating the networks with the visNetwork package if the wrangling is completed, and look into customizing the networks or adding more variables/potential interactive features if she has time.

- Henry will scrape data from local newspapers from all 50 states for different times during the pandemic, and wrangle the data into a tidy data frame. He will also use the TwittR package to obtain tweets with locations from different temporal points during the pandemic, and create a separate data frame with that text data. Finally, he will also begin a sentiment analysis.	

- Helen will wrangle a previous dataset to include the 1-4 ranking options for the 5 mental health symptoms and access variables. She will try clustering with the 1-4 ranking and the “y/n” distinction (which is what we previously used for the Shiny app) and choose the appropriate way to move forward based on the results. She may also take a pass through the Pulse data dictionary and consider pulling more variables out related to health. She might even take a look at the dimension reduction.

**Comment by bebailey** [comment]
Sounds great! There's room to scale back, if needed. Just a heads up about scraping from twitter: there's like a 5000 historical tweet limit (anything beyond a week ago). The data may not be as rich as you hope, there. Also, I've learned from another group of students that **rtweet** might be a better package and is well-documented (check out their vignettes).

This was not part of the requirement, but please make sure you discuss amongst yourselves exactly how you plan to divide up the work. Perhaps it would be useful to write it down as a sort of group contract, even. To the degree possible, we want equitable contributions to the core components of the blog, with flexibility for any individual to go "above and beyond" on any particular aspect of interest to them. 

---

To embed a shiny app, you can use a code chunk (see [this link](https://bookdown.org/yihui/bookdown/web-pages-and-shiny-apps.html) for details):

```
knitr::include_app("https://your-account.shinyapps.io/your-app/", height = "600px")
```

**Comment by thuang2023** [comment]
**### Status Update #1**
Henry scraped article titles from different weeks from the most circulated news source of each state, and put it into a cleaned dataset with three columns; the state, the week, and the article title. He has achieved the work he has expected up to this point, although he still needs to take a look at scraping Twitter data. The web scraping of the articles took longer than expected since some of the urls did not have clear access, but the Twitter data should go a bit quicker. Next week, he will start on the visualizations, such as doing the sentiment analysis map and word clouds. 

Tracy wrangled all the restrictions datasets to be in a format for networks, with three columns; the state to, the state from, and the number of days in 2020 where they shared the same restrictions. She also started working on the Shiny app with the visNetwork package, where users can select which states they want to look at, as well as which type of restrictions (i.e. gathering bans, mask mandates, etc.) they want to visualize. The nodes are colored by the annual proportion of COVID cases, and the edges are weighted by the number of days. She has achieved the work she has expected up to this point, and next week, she will look into polishing the Shiny app and adding more interactive features (such as changing the node color by another variable).

Helen did clustering on all the different racial/ethnic groups, using different sets of variables. She also created 3D plots of the clusters. She is not sure if the clustering results so far are worth keeping because it’s not clear that they are clearly clustering into the racial/ethnic groups, but she will look into clustering a bit more and possibly shift to doing a network or map with the different racial/ethnic groups if clustering does not give any meaningful results. She has achieved the work she has expected up to this point.

**Comment by thuang2023** [comment]
**Status Update 2**
Henry has finished scraping and cleaning data from different news sources from different states, and has decided not to use Twitter data because the news source data provides enough information. He has started on creating an interactive map in Shiny for sentiment analysis of text in different states at different timepoints of the pandemic, as well as word clouds for exploring the most common words found in the news article titles. 

Tracy finished working on the Shiny app with the visNetwork package, and made some small changes such as changing the state names and allowing users to hover over the edges to see the exact number of days each pair of states had the same COVID restrictions in 2020. She also is cleaning up the R shiny app and data wrangling files, and will polish the Shiny app to have interactive titles and a more aesthetically pleasing layout. She will also start on the blog writing for the state restrictions networks. 

Helen decided to cluster on the three mental health care variables and a fourth variable that marks whether or not the individual has a healthcare plan. While the distribution of racial/ethnic groups within the clusters show deviation from the distribution of racial/ethnic groups for all respondents, the clusters are not clear representations of these groups. Helen has decided to include the results in the final blog, and will work on an interactive 3D plot to represent the clusters (by plotting 3 of the 4 variables at a time). She will work on extracting more information about the clusters (i.e., how the 4 variables actually compare across the clusters). She tried some SVD for fun but quickly realized it would not be very useful. She will begin on a network that connects the racial/ethnic groups and weights the edges based on interactive elements - choosing which variables (e.g., depression symptoms or prescription medication) to weight by.
